### ISSUE TITLE
Tradução do capítulo 3 (Git Branching > Branch Management)

### ISSUE THREAD

**Issue by radiegues06** [progit/progit2-pt-br#34]
Olá pessoal!

Gostaria de contribuir com a tradução. 
Vou iniciar a tradução da seção "3.3 Git Branching - Branch Management", tudo bem?

Abraços
Rafael

**Comment by carlosschults** [comment]
@radiegues06 Olá Rafael! Obrigado pelo interesse em colaborar com o projeto de tradução. Seja muito bem-vindo.

Pode iniciar o trabalho neste arquivo. Tente dar uma lida em outros trechos já traduzidos, para ter uma ideia das convenções e padrões que vem sendo utilizadas. Por exemplo, existem situações nas quais nós optamos por deixar certos termos em inglês mesmo, porque traduzí-los soaria estranho.

Outra coisa: eu acabei de atualizar este repositório, sincronizando o arquivo que você vai traduzir com a versão original no repositório em inglês. Então, certifique-se por favor de fazer um `git pull` antes de iniciar sua tradução, para que você tenha a versão mais atualizada do arquivo.

Qualquer dúvida ou qualquer outra coisa, estamos à disposição.

Abraço.

**Comment by sergiocabral** [comment]
Estou escrevendo esse comentário em todos os issues... apenas para dizer que padronizei o título para ficar mais fácil a identificação de onde o trabalho da galera está. Se por acaso errei ao descrever o que está fazendo, desculpe e, por favor, faça o ajuste. 🙏

**Comment by sergiocabral** [comment]
@radiegues06, passando aqui apenas para dizer que parece ter havido algum conflito de trabalho na tradução do capíutlo 3.

(Foi por conta de problemas no build do PDF com o Travis CI que acabou atrasando os merges.)

O @altemirpacheco fez a tradução completa, pelo que parece, de todos os arquivos do capítulo 3.

Mas você iniciou a tradução primeiro. Então talvez o merge possa ser feito com suas alterações e na sequência usar as alterações do @altemirpacheco após a sua como uma forma de revisão adicional.

O que acha?

**Comment by radiegues06** [comment]
Olá @sergiocabral , obrigado pela atualização. Eu acabei não realizando muitos avanços na tradução, infelizmente. Mas posso ajudar na revisão. 

Creio que podemos avançar com a tradução que o Altemir já realizou.

Muito obrigado desde já!

**Comment by sergiocabral** [comment]
@radiegues06 beleza? Valeu pelo retorno. Vou fechar essa issue e seguimos em frente. Querendo abrir nova issue para sinalizar o começou de tradução de um novo capítulo é só fazer. ✌💪
