### ISSUE TITLE
Tradução do  arquivo "1-setting-up-account.asc"

### ISSUE THREAD

**Issue by Cupnodes** [progit/progit2-pt-br#36]
Olá equipe de tradução!
==============

Gostaria de colaborar traduzindo o arquivo **"1-setting-up-account.asc"** do capítulo 6.
Preciso de algo além do AsciiDoc?

**Comment by carlosschults** [comment]
@Cupnodes Olá! Obrigado pelo interesse em contribuir com a nossa tradução.

Caso você não queira gerar o livro localmente, nem precisa do AsciiDoc. Apenas faça a tradução, usando qualquer editor de texto que você queira usar. Ao enviar o pull request, o processo de CI vai detectar caso exista algum erro.

**Comment by carlosschults** [comment]
@Cupnodes Ah, só mais uma coisa que esqueci. Dê um `git pull` antes de começar, porque eu acabei de atualizar o arquivo que você vai traduzir, para que esteja sincronizado com o livro original em inglês.

**Comment by Cupnodes** [comment]
Ja fiz o `git pull`, quando terminar a tradução só preciso fazer rodar `git push` ?

**Comment by Cupnodes** [comment]
Só uma dúvida, o arquivo que eu tenho que traduzir está na pasta 'book' ou 'book-en' ?

**Comment by carlosschults** [comment]
@Cupnodes Seria o da pasta 'book'. O da pasta 'book-en' é basicamente uma cópia do arquivo original em inglês para referência.

**Comment by Cupnodes** [comment]
@carlosschults Terminei a tradução, só que agora fiz o commit e não estou conseguindo fazer push, o que faço agora ?

**Comment by carlosschults** [comment]
@Cupnodes Você pode executar `git status`, tirar um print da tela e mandar por aqui?

**Comment by Cupnodes** [comment]
![error](https://user-images.githubusercontent.com/51294145/89899729-17072b80-dbb9-11ea-946d-59211d1f2b18.png)

**Comment by carlosschults** [comment]
@Cupnodes Hum, entendi. Você está trabalhando no master. Você vai precisar criar um branch separado e dar push nele. Faça o seguinte:

1. Crie um novo branch e mude para ele:
`git checkout -b translate-file`

2. Dê o push no branch:
`git push -u origin translate-file`

3. Acesse este repositório pelo GitHub, e você verá uma mensagem dizendo que fez o push recentemente, e um botão criar pull request.

4. Depois que o pull request for criado com sucesso, volte para o branch `master` e reset ele para onde estava antes:
`git checkout master`
`git reset --hard HEAD~1`

**Comment by Cupnodes** [comment]
![error](https://user-images.githubusercontent.com/51294145/89904607-86801980-dbbf-11ea-84d0-0e7131694390.png)

@carlosschults   Certo, mas quando fiz o push ele me nega o acesso

**Comment by carlosschults** [comment]
Aparentemente, você está tentando dar push nesse repositório aqui. Você precisa dar o push para o seu fork. 

Faz o seguinte: dá um `git remote -v` e mostra o resultado aqui, por favor.

**Comment by Cupnodes** [comment]
![error](https://user-images.githubusercontent.com/51294145/89906435-c516d380-dbc1-11ea-8942-d79c4cf49dfe.png)

**Comment by carlosschults** [comment]
Sim, foi isso mesmo. Você deu clone deste repositório aqui, e não do seu fork. Vai dar um pouco de trabalho, mas vamos arrumar.

1. Faça uma cópia do arquivo traduzido. Guarde em um local seguro porque você vai precisar depois.

2. Exclua o repositório atual do seu computador (ou renomeie, para ter mais segurança.)

3. Clone o seu fork com o comando:

`git clone https://github.com/Cupnodes/progit2-pt-br.git`

4. Acesse o repositório pela linha de comando e crie um novo branch:

`git checkout -b translate-file`

5. Substitua o arquivo que você está traduzindo, dentro da pasta book, pelo arquivo traduzido que você copiou e guardou no passo 1.

6. Dê commit:

`git commit -a -m "Mensagem de commit"`

7. Dê o push:

`git push -u origin translate-file`

8. Crie o pull request pela interface do GitHub.

**Comment by Cupnodes** [comment]
@carlosschults Muito obrigado! (essa foi minha primeira contribuição Open Source)
Na próxima vez que for contribuir, tem alguma dica para um iniciante?
Outra questão, posso continuar contribuindo com traduções de outros capítulos? (Agradeço desde já) 👍

**Comment by Cupnodes** [comment]
![error](https://user-images.githubusercontent.com/51294145/89911211-88e67180-dbc7-11ea-8fec-a91e16502762.png)
@carlosschults  Essa notificação é importante ou apenas um detalhe secundário?

**Comment by carlosschults** [comment]
> @carlosschults Muito obrigado! (essa foi minha primeira contribuição Open Source)

Que legal! Fico feliz em saber. Minha primeira contribuição foi auxiliar na tradução da primeira edição deste livro, por volta de 2012 :)

> Na próxima vez que for contribuir, tem alguma dica para um iniciante?

Acho que vou atualizar o `readme` do projeto, deixando mais dicas de como fazer os procedimentos.

> Outra questão, posso continuar contribuindo com traduções de outros capítulos? (Agradeço desde já) 👍

Claro, sem problema. Apenas [crie uma issue](https://github.com/progit/progit2-pt-br/issues/new) antes para não correr o risco de pegar algo que outra pessoa já esteja trabalhando.

**Comment by carlosschults** [comment]
> ![error](https://user-images.githubusercontent.com/51294145/89911211-88e67180-dbc7-11ea-8fec-a91e16502762.png)
> @carlosschults Essa notificação é importante ou apenas um detalhe secundário?

Deu algum erro na geração do livro. Vou verificar.

**Comment by carlosschults** [comment]
@Cupnodes Eu criei um guia para ajudar quem não tem muita familiaridade em contribuir com projetos open-source:

[](https://github.com/progit/progit2-pt-br/blob/master/beginners-guide.asc)

Se você puder ler e dar um feedback, seria muito útil :D

**Comment by Cupnodes** [comment]
@carlosschults 
>Eu criei um guia para ajudar quem não tem muita familiaridade em contribuir com projetos open-source:

Ficou excelente, acho interessante colocar boas práticas para quem está começanco.

**Comment by carlosschults** [comment]
Solved by #38
