### ISSUE TITLE
Tradução do capítulo 5

### ISSUE THREAD

**Issue by flaviovisnardifilho** [progit/progit2-pt-br#43]
Olá, tudo bem? 

Eu gostaria de contribuir. Não vi ninguém com PR ou Issue aberto sobre o capítulo 5, então peguei este.

Eu comecei o primeiro arquivo deste capítulo, e utilizei a versão em inglês que parece mais atualizada que esta. Parece que a versão em pt_br está na 2.0.0 e o doc em inglês na 2.8.0.

Preciso adequar o texto para os padrões que estão sendo utilizados. Estou vendo as traduções dos capítulos 1, 2 e do pedaço do 3º, mais a PR de @Cupnodes  do capítulo 6 para ter uma ideia. Alguma sugestão?

**Comment by carlosschults** [comment]
@flaviovisnardifilho Olá! Seja bem vindo e obrigado pelo interesse em contribuir com o projeto.

Por favor, antes de enviar a PR da tradução, envie uma outra contendo apenas a atualização do arquivo em inglês para a versão mais atual. Aí fica mais fácil revisar a tradução depois.

Qualquer dúvida, estamos à disposição.

**Comment by flaviovisnardifilho** [comment]
Obrigado, @carlosschults! Segue PR #44

**Comment by flaviovisnardifilho** [comment]
Acho que você estava se referindo aos arquivos da seção em português mesmo, não é? Eu fiz outra PR com as alterações no livro em português #45

**Comment by carlosschults** [comment]
@flaviovisnardifilho Obrigado! Vou tentar revisar até o final da semana, ok?

**Comment by flaviovisnardifilho** [comment]
Combinado, @carlosschults!

**Comment by flaviovisnardifilho** [comment]
Enviei o primeiro arquivo para revisão, @carlosschults. #46
