### ISSUE TITLE
Tradução do capítulo 3.1 (Git Branching > Branches in a Nutshell)

### ISSUE THREAD

**Issue by lucasoshiro** [progit/progit2-pt-br#55]
Olá!

Estou começando a tradução do arquivo nutshell.asc

**Comment by carloscartola** [comment]
Oi!

O projeto está ativo? Pergunto, pois pensei em ajudar na tradução, mas vi várias mensagens antigas sobre traduções que ainda não foram disponibilizadas e algunas, como essa, sem resposta.

Abraços, Cartola.

**Comment by altemirpacheco** [comment]
Queria saber o mesmo

Att:

Altemir Nunes Pacheco

Em dom, 4 de abr de 2021 08:10, carloscartola ***@***.***>
escreveu:

**Comment by carlosschults** [comment]
Olá, @lucasoshiro , @altemirpacheco e @carloscartola. 

Agradeço pelo interesse em contribuir com o projeto, e peço desculpas pela demora em responder.

O que está acontecendo é que o projeto está com problema no build, provavelmente devido a uma mudança recente no Travis CI, o serviço usado para dar o build no projeto a cada pull request concluído.

Devido a este problema, eu não posso aceitar e integrar nenhum pull request, por mais simples que seja, pois iria fazer o build quebrar. E ultimamente, devido a compromissos profissionais, eu tenho estado sem tempo para investigar e corrigir o problema.

Peço desculpas mais uma vez pelo atraso. Se tudo der certo, esta semana pretendo tirar um tempo para corrigir esta falha no build e então poder ir revisando e aceitando os PRs na fila.

**Comment by carloscartola** [comment]
Legal Carlos, se puder ajudar de alguma forma ou se tiver novidades é só
falar.

Um abraço,

Carlos E G Carvalho (Cartola)
http://cartola.org/360
http://www.panoforum.com.br/


Em dom., 4 de abr. de 2021 às 14:01, Carlos Schults <
***@***.***> escreveu:

**Comment by sergiocabral** [comment]
Estou escrevendo esse comentário em todos os issues... apenas para dizer que padronizei o título para ficar mais fácil a identificação de onde o trabalho da galera está. Se por acaso errei ao descrever o que está fazendo, desculpe e, por favor, faça o ajuste. 🙏

**Comment by lucasoshiro** [comment]
Oi @sergiocabral! Acho que é melhor seguir com as alterações do @altemirpacheco, assim fica mais próximo do resto do capítulo! Vou fechar meu PR

**Comment by sergiocabral** [comment]
@lucasoshiro obrigado pelo retorno e compreensão. Espero que, sendo possível, você possa continuar colaborando com o projeto.
