### ISSUE TITLE
Tradução do capítulo 3 (Git Branching)

### ISSUE THREAD

**Issue by altemirpacheco** [progit/progit2-pt-br#60]
Pessoal, vou procurar colaborar traduzindo o capítulo 3.  #58

**Comment by altemirpacheco** [comment]
Terminei a tradução desse capítulo.

**Comment by sergiocabral** [comment]
Boa tarde, @altemirpacheco. Para você submeter seu trabalho você precisa abrir um pull request neste repositório. Sabe como fazer? Precisa de ajuda?

**Comment by altemirpacheco** [comment]
Pois é! Eu já fiz isso. É o Pull Request https://github.com/progit/progit2-pt-br/pull/58. Já completei a tradução. Será que faltou alguma coisa pra ele ser analisado?

**Comment by sergiocabral** [comment]
Legal, @altemirpacheco. Acabei de ver aqui. Estou lendo os commits e assim que terminar vamos inserir seu trabalho no branch principal.

@carlosschults estou revisando o texto traduzido, tudo bem? Tendo sugestão não deixe de me falar.

**Comment by altemirpacheco** [comment]
Obrigado @sergiocabral ! Se precisar alguma correção é só me avisar.

**Comment by sergiocabral** [comment]
Estou escrevendo esse comentário em todos os issues... apenas para dizer que padronizei o título para ficar mais fácil a identificação de onde o trabalho da galera está. Se por acaso errei ao descrever o que está fazendo, desculpe e, por favor, faça o ajuste. 🙏

**Comment by sergiocabral** [comment]
@altemirpacheco tudo bem? Estou revisando seu texto ainda... São muitos arquivo rsrsrsrs Obrigado pelo trabalho.

Percebi uma situação delicada aqui... Depois que organizei os nomes das issue ficou claro que mais pessoas traduziram o capítulo 3.

Você traduziu ele inteiro?

Talvez eu faça o merge da tradução deles primeiro. E depois, ao fazer o merge da sua tradução, eu faça a comparação para escolher as frases entre um e outro.

O que acha?

**Comment by altemirpacheco** [comment]
@sergiocabral  eu traduzi o capítulo inteiro. Então a sua sugestão de fazer o merge deles primeiro é a melhor opção.

**Comment by sergiocabral** [comment]
@altemirpacheco, mais uma vez parabéns e obrigado.

Assim que o livro for compilado é sempre bom baixarmos ele e lermos no PDF nossa tradução para conferir o texto e a formatação, pra sabe se ficou tudo certo como o esperado.

Mas talvez já queira fechar essa issue.

**Comment by altemirpacheco** [comment]
Obrigado @sergiocabral ! Vou fechar por aqui e depois vou ler todo o conteúdo novamente. Sempre fica alguma coisa pra melhorar. Fique a vontade pra fazer as correções que considerar necessárias.

**Comment by sergiocabral** [comment]
@altemirpacheco, legal. Não posso deixar de agradecer a ajuda de ontem com o subscribe no canal.  brigadão. grande incentivo
