### ISSUE TITLE
Traduções e correções gramaticais

### ISSUE THREAD

**Issue by shockyng** [progit/progit2-pt-br#78]
Olá pessoal, primeiramente, parabéns pelo trabalho que tem sido feito com esta obra, será de grande proveito para a comunidade brasileira!

Tenho interesse em ajudar tanto na tradução do livro quanto em correções de gramaticais.

Dei uma lida nas instruções de contribuição para começar. 

Estive lendo o trabalho já realizado e percebi que em alguns momento há ausência de pronomes relativos, acredito que pelo fato de muitas vezes eles serem omitidos em inglês, o que pode não ajudar na fluidez da leitura. Um exemplo disto é a sessão: O básico do Git - Imagens, Não diferenças. A frase inicial desta sessão diz: ``"A principal diferença entre Git e qualquer outro VCS (Subversion e similares) é a maneira Git trata seus dados"``. Uma tradução mais fluida seria algo como: ``é a maneira que o Git trata seus dados``. 

Gostaria de saber se é possível contribuir tanto com traduções, bem como com correções gramaticais como no exemplo acima citado.

Obrigado!

**Comment by sergiocabral** [comment]
Acho bem válido. Brigadão @shockyng ... pode enviar seus pull requests, sim.
