### ISSUE TITLE
New translator and maintainer for progit2-en

### ISSUE THREAD

**Issue by sergiocabral** [progit/progit2-pt-br#8]
Hello people.

I am here to help and follow the mode of operation of the current maintainers.

I would like to be listed as one of the merge approvers for progit2-en translations.

My interest is to complete the translation of the book into Brazilian Portuguese as soon as possible. I want to use the book as a way of guiding people in my work circle.

Jean-Noël (@jnavila),Carlos (@carlosschults) and others, what do you think?

**Comment by carlosschults** [comment]
I think this is fantastic, all help is welcome!

**Comment by sergiocabral** [comment]
Thank you. Feel free to help me and guide me where you think it is necessary.
