### ISSUE TITLE
Erro 502 - https://progit.org/translations

### ISSUE THREAD

**Issue by vanribeiro** [progit/progit2-pt-br#9]
Eu gostaria de contribuir com a tradução, contudo, conforme indicado na página [Contribuindo com o Pro Git (2ª Edição)](https://github.com/progit/progit2-pt-br/blob/master/CONTRIBUTING.md#contribuindo-com-o-pro-git-2%C2%AA-edi%C3%A7%C3%A3o), tópico [Traduções](https://github.com/progit/progit2-pt-br/blob/master/CONTRIBUTING.md#tradu%C3%A7%C3%B5es), eu deveria acessar o  https://progit.org/translations para me informar de como fazer a minha colaboração no projeto, mas ela está retornando o erro 502. Existe alguma outra forma de eu me informar à respeito? Desde já, muito obrigada!

**Comment by carlosschults** [comment]
Olá, @vanribeiro. Com relação ao erro 502 naquele link, de fato é um problema. Vou abrir uma issue no repositório original para que alguém possa corrigí-lo.

Por enquanto, você pode ignorar aquele link e enviar as suas contribuições na forma de pull requests para este repositório.

**Comment by vanribeiro** [comment]
Ok, @carlosschults! Obrigada pelo retorno! :-)
